### ISSUE TITLE
file package in npm fails to install

### ISSUE THREAD

**Issue by reid** [mikeal/node-utils#1]
The file tarball in npm's registry isn't a valid tarball:

$ npm install file@latest
The "ini" module will be removed in future versions of Node, please extract it into your own code.
npm configfile /Users/rburke/.npmrc
npm sudo false
npm cli [ 'install', 'file@latest' ]
npm install pkg file@latest
npm fetch data file
npm GET file
npm install pkg file@latest
npm install pkg file@0.1.1
npm readJson /Users/rburke/.node_libraries/.npm/.cache/file/0.1.1/package.json
npm GET file/0.1.1
npm fetch http://registry.npmjs.org/file/-/file-0.1.1.tgz to /Users/rburke/.node_libraries/.npm/.cache/file/0.1.1/package.tgz
npm content-length unknown
npm fetch finished
npm bytes 5450
npm exec tar "xzf" "/Users/rburke/.node_libraries/.npm/.cache/file/0.1.1/package.tgz" "--strip" "1" "-C" "/Users/rburke/.node_libraries/.npm/.cache/file/0.1.1/package"
tar: Unrecognized archive format: Inappropriate file type or format
tar: Error exit delayed from previous errors.
npm fail Error installing file@0.1.1

npm ! Error: `tar` failed with 1
    at ChildProcess.<anonymous> (/usr/local/Cellar/npm/0.1.13/libexec/lib/utils/exec.js:24:18)
    at ChildProcess.emit (events:32:26)
    at Stream.<anonymous> (child_process:108:12)
    at Stream.emit (events:25:26)
    at net:879:12
    at EventEmitter._tickCallback (node.js:48:25)
    at node.js:204:9

npm failure try running: 'npm help install'
npm failure Report this _entire_ log at http://github.com/isaacs/npm/issues
npm failure or email it to npm-@googlegroups.com

**Comment by mikeal** [comment]
Fixed a while ago, this is a super old bug.
