### ISSUE TITLE
Change 'sys' to 'util' for node v0.6 compliance

### ISSUE THREAD

**Issue by Sannis** [mikeal/node-utils#14]
I can do this if you agree and explain your supported versions policy for me (I've been surprised about node >= 0.1.99 in package.json).

**Comment by aconbere** [comment]
See this issue

https://github.com/mikeal/node-utils/issues/15 for more details but I'm migrating this project into it's own repository here

https://github.com/aconbere/node-file-utils

**Comment by Sannis** [comment]
Thanks, I'll use your module :)
