### ISSUE TITLE
fileutil.mkdirs not working on osx 10.7.2

### ISSUE THREAD

**Issue by paulmillr** [mikeal/node-utils#16]
node 0.6, osx 10.7.2.

mkdirs doesn't work, producing `Error: ENOENT, no such file or directory '...'` when trying to create directory `...`.

Although, mkdirsSync works.

**Comment by aconbere** [comment]
For some reason I appeared to have missed a possible error when hitting non existent files.

I've recently moved this project to

https://github.com/aconbere/node-file-utils

I believe this issues is fixed there.
