### ISSUE TITLE
SELF_SIGNED_CERT_IN_CHAIN error

### ISSUE THREAD

**Issue by aterreno** [mikeal/node-utils#25]
I wonder if this one is an error from NPM or it happens because of request. 

I've tried with different versions of node/npm but no luck, 

v0.11.14
v0.10.33
v0.10.9
v0.10.26

the root npm install is:  npm install -g cordova ionic

npm http GET https://registry.npmjs.org/request/-/request-2.27.0.tgz
npm ERR! Error: SELF_SIGNED_CERT_IN_CHAIN
npm ERR!     at SecurePair.<anonymous> (tls.js:1370:32)
npm ERR!     at SecurePair.EventEmitter.emit (events.js:92:17)
npm ERR!     at SecurePair.maybeInitFinished (tls.js:982:10)
npm ERR!     at CleartextStream.read [as _read](tls.js:469:13)
npm ERR!     at CleartextStream.Readable.read (_stream_readable.js:320:10)
npm ERR!     at EncryptedStream.write [as _write](tls.js:366:25)
npm ERR!     at doWrite (_stream_writable.js:226:10)
npm ERR!     at writeOrBuffer (_stream_writable.js:216:5)
npm ERR!     at EncryptedStream.Writable.write (_stream_writable.js:183:11)
npm ERR!     at write (_stream_readable.js:583:24)
npm ERR!     at flow (_stream_readable.js:592:7)
npm ERR!     at Socket.pipeOnReadable (_stream_readable.js:624:5)
npm ERR! If you need help, you may report this _entire_ log,
npm ERR! including the npm and node versions, at:
npm ERR!     http://github.com/npm/npm/issues

**Comment by usagene** [comment]
Bump up... received the same error just recently.

**Comment by aterreno** [comment]
BTW, I found out why I got this, it was after installing
https://github.com/fix-macosx/fix-macosx

So if you messed around with packet filtering and SSL tracing there's a
good chance you are in the same pot
