### ISSUE TITLE
request - relative location redirects don't work

### ISSUE THREAD

**Issue by dylang** [mikeal/node-utils#6]
This should work:

header: {
  location: '../wtf.html'
}

Yeah, not standard, but sites do this crap.

**Comment by chrisirhc** [comment]
Take a look at:
martymcguire/node-utils@5032aef0d56895eba79fc36ae0219adf4d448701

**Comment by DTrejo** [comment]
+1

Thanks for that commit chris. Hopefully it gets merged soon so that bad sites won't break request and everything it depends on (http-agent, http-console, etc).

**Comment by DTrejo** [comment]
If you need another site to test this on, http://www.express.com is an offender.

**Comment by mikeal** [comment]
I checked in a fix to master.

I don't have a test case so I can't be 100% on it.

Looking through the code for url.resolve it's a lot of extra overhead to do this for every foward so I only do it when the location is absolute or relative.
