### ISSUE TITLE
responseBodyStream HTTP headers

### ISSUE THREAD

**Issue by Poetro** [mikeal/node-utils#8]
No HTTP headers are passed to the response stream, and there is no option to pass any based on the response. At least the response's status, content-type and content-length should be written to responseBodyStream.

**Comment by mikeal** [comment]
In node only the response body is sent as a stream so we can only pump the body to another stream.

We have two options. One is that we can add a one-off method to responseBodyStream or we can fire the callback right after the headers when we have a responseBodyStream and rely on the end event. Either way it's a fairly big change.

**Comment by Poetro** [comment]
<script src="https://gist.github.com/668369.js"> </script>

https://gist.github.com/668369
seems to work for me atm, but handling errors would be great.

**Comment by mikeal** [comment]
That works but it's not ideal because that response body is going to have to buffer the entire thing before you call writeHead(). What you really want is an event for the headers that you can use to writeHead() and then have the response body stream right to the socket.

**Comment by mikeal** [comment]
That works but it's not ideal because that response body is going to have to buffer the entire thing before you call writeHead(). What you really want is an event for the headers that you can use to writeHead() and then have the response body stream right to the socket.

**Comment by Poetro** [comment]
I've just read some interesting article about these kind of stuff http://journal.paul.querna.org/articles/2010/09/04/limiting-concurrency-node-js/ might give some ideas.
