### ISSUE TITLE
add maxRedirects to throw error on redirect loops

### ISSUE THREAD

**Issue by Marak** [mikeal/node-utils#9]
it's possible to get stuck in a redirect loop and request never fires its error handling.

this behavior is somewhat confusing as a user has no idea they are in a redirect loop.

maxRedirects should default to a relatively low number, and then fire callback with max redirects error.

**Comment by mikeal** [comment]
maxRedirects is current set to 10, the problem was that we weren't actually throwing when exceeding the max redirects.

Fixed in master, emits error on the client object when exceeding maxRedirects so it can be handled either on the client object or in the request callback.
